layout_spectrum: 0.833430903730914
typography_spectrum: 0.8054986307397485
color:
  brandStrength: 0.32605405035428703
  lightness: 0.8995894226245582
  saturation: 0.5515248728916049
  rhythmicContrast: 0.038987809559330344
  brandColors:
    - '#FFFFFF'
    - '#0C4569'
    - '#9F9F9F'
    - '#009176'
    - '#717173'
name: McAtee HVAC & Plumbing
